/* tslint:disable:max-line-length */
import { Game } from './models/game';

const games: Game[] = [
  {
    id: 1,
    url: `halluta`,
    name: `Halluta`,
    spaces: [`Outdoors`, ],
    description: `Very similar to kickball, but with a few twists. Players are divided into two teams, one team in the field, one team kicking. Everyone on the kicking team will get a chance to kick each half-inning, the so the teams switch after the final kicker. Players score a point for their team by crossing homeplate. However, rather than being done when crossing home, players may continue on to first base and keep running the bases until they are tagged out. Players must yell "Halluta" at the top of their lungs when crossing home plate, and may not stop at home in between kickers, they must run all the way to first or go back to third. There is no limit to how many runners can be on one base at a time. Depending on time, you can play one or two full innings, and the team with the most runs wins.`,
    events: [`Youth Group`, `Summer Camp`, `SGU`, ],
    settings: [`Organized`, ],
  },
  {
    id: 2,
    url: `ultimate-arena`,
    name: `Ultimate Arena`,
    spaces: [`Outdoors`, ],
    description: `Basically dodgeball with no separation of the field, use of different projectiles/weapons (balls, finger rockets, pool noodles, etc.) and several barriers in a square arena. Normal dodgeball rules: get hit = out, catch projectile = safe, throw and gets caught = out. Jailbreaks can be called by the game leader. Can be played individually or with teams. INDIVIDUAL: All players in the arena, fighting until last player standing. Players start lined up along the sidelines. You can run ANYWHERE in the play field. Game is played until there is one player left standing. TEAMS: Play tournament style w/4 teams, i.e. teams 1 and 2 play, teams 3 and 4 play, 1st round losers play, first round winners play. Each team stands on a different side of the field. Same rules as individual but no jailbreaks, players can only get back in by teammate catching a projectile or bonus football. The bonus football is thrown into the arena mid-game by the facilitator, who is holding a hula hoop along one of the sidelines. If a player throws the football through the hula hoop, they get 5 players back in for their team. If they are hit before they can throw it they must drop it. If the football goes out of bounds without going through the hoop, a leader can throw it back in.`,
    events: [`Summer Camp`, ],
    settings: [`Organized`, ],
  },
  {
    id: 3,
    url: `barge-battle`,
    name: `Barge Battle`,
    spaces: [`Outdoors`, ],
    description: `A one on one duel for supremacy on the high seas! Setup an inflatable raft upside down in 2 to 3 feet of water. Select 2 students (same gender, similar size or age) from opposing teams and give each a helmet, life jacket, and jouster. Example jouster: PVC inside a pool noodle, with bubble wrap around the ends and the whole thing covered in duck tape. The combatants stand on opposite ends of the raft. Have one leader in the water per raft, to help stabablize it a little. When the facilitator says go or blows an air horn, the combatants try to knock/wrestle each other off the raft. The first one off the raft loses. Points are awarded to teams based on their overall win percentage. Game Twist: Have the leader in the water shake or spin the boat.`,
    events: [`Summer Camp`, ],
    settings: [`Organized`, ],
  },
  {
    id: 4,
    url: `sand-sculpture`,
    name: `Sand Sculpture`,
    spaces: [`Outdoors`, ],
    description: `Teams of students build a sand castle, sculpture, or creative work of art for the judge(s). Multiple team builds are allowed. The judge(s) score each team's work at the end.`,
    events: [`Summer Camp`, ],
    settings: [`Organized`, ],
  },
  {
    id: 5,
    url: `dune-jump`,
    name: `Dune Jump`,
    spaces: [`Outdoors`, ],
    description: `Meant to be played at the beach. Leaders find and/or buid a sand dune. Players (divided into teams) then take turns running and jumping off the dune, each attempting to go as far as possible. The longest jump for each team is marked. Players must jump from behind a designated line marked in the sand, failure to do so results in disqualification of the jump. Players may jump again after all participants have had a chance. Jumps are measured by the furthest back mark the jumper makes in the sand. For example, if a jumper initially lands on their feet, but falls back onto their butt, the jump is measured to the butt mark. Points are awarded to each team based on the place of there longest jump.`,
    events: [`Summer Camp`, ],
    settings: [`Organized`, ],
  },
  {
    id: 6,
    url: `extreme-evaders`,
    name: `Extreme Evaders`,
    spaces: [`Outdoors`, ],
    description: `Similar to an obstacle course, setup an area with a defined starting line and endzone. Players are divided into teams and one team at a time runs the field.  Other teams stand on perimeter of the field watching. The goal is to get the most points by getting your team to the end zone. Cones will create running lanes that players must stay within. Opposing team's leaders will stand behind the field perimeter and fire finger rockets & dodgeballs at the team on the field. If a player is hit by dodgeball or finger rocket, they are out. They stand on the perimeter of the field. The game facilitator stands at the goal line and counts how many players make it into the endzone without getting hit. Each team should select one person to carry the team flag; if this person makes it to the endzone they count for significantly more points. More roles can be introduced in subsequent rounds. For example, select two team members to be "bodyguards". Bodygaurds get shields to protect their teammates, but don't earn points for the team by making it to the endzone. Or give students the option to navigate the course piggy-backing on another student for bonus points. After each team has gone the determined number of rounds, the team with the most points wins. Game Twist: No teams, have all the students run at once, with all the leaders on the outside. Any student that makes it goes back to the start and gets to run the next round. Last student standing wins.`,
    events: [`Summer Camp`, ],
    settings: [`Organized`, ],
  },
  {
    id: 7,
    url: `capture-the-flag`,
    name: `Capture the Flag`,
    spaces: [`Outdoors`, ],
    description: `Also known as 'Capture the Noodle' when using pool noodles as flags. Divide a large playing area into two sides and players into two teams. Be sure to clearly mark the dividing line so players can easily tell. Mark off a small "jail" somewhat deep into each team's territory. Each team is given a flag and must hide it somewhere in their area, making sure that nobody from the opposing team can see where it is. Flags must be hidden in a place where it can actually be seen, not under a car, buried in a bush, or up in a tree. Teams are given a few minutes to hide their flags, and the game begins. In order to win the game, a player must capture the other team's flag and bring it back to their team's territory. If a player ventures onto the opponent's side, they may be tagged and sent to that team's jail. Players can escape jail by being rescued by a teammate who makes it all the way to them in jail without being tagged. If this happens both the rescuing player and the rescued player must return to their own side immeadiatly, but cannot be tagged while doing so. The game facilitator may also call a jailbreak, thereby freeing all prisoners on both teams. If a player is tagged while carrying the other team's flag, the flag can either be placed back at its original location or left where the player was tagged; the facilitator should make this desicion before the game begins. Defending players should not stand within 10-15 feet of their flag unless chasing an opponent (no puppy guarding).`,
    events: [`Summer Camp`, `SGU`, ],
    settings: [`Organized`, ],
  },
  {
    id: 8,
    url: `mission-impossible`,
    name: `Mission Impossible`,
    spaces: [`Outdoors`, ],
    description: `Classic Glenwood night game. Split the students into 2-4 teams. Each team is assigned a different color of flaging tape, and each team member will have a small length tied onto their wrist so that it is visible. Hidden somewhere on the property, a leader will be waiting to collect the tape from the students. The student's goal is to find this leader and give him/her their wristband. If they suceed, they may return to the starting point, get another wristband, and attempt to find the leader again. The catch is that the other leaders will be roaming and sneaking around, trying to catch the students before they make it to the designated leader. These leaders catch the students by shining their flashlight on them. The leader can then take the student's wristbands or they can make them do something silly like sing Justin Bieber at the top of their lungs as "payment" and then let them go free. Coming up with creative "payments" is highly encouraged. If the leader is not feeling generous and takes the student’s wristband, then the student can go back to base where a leader will give them another wristband. Students may only have one wristband at a time. Glowsticks can be hidden throughout the playing area. If a player finds it and delivers it to the designated leader, they earn X number of points for their team. Glowsticks should be carried in the open, not stuffed in to a pocket or under a shirt, making it harder for students to be sneaky. At the end of the time, all the lengths of tape and glowsticks successfully delivered are counted up and the team with the most points wins.`,
    events: [`Fall/Winter Retreat`, `Summer Camp`, ],
    settings: [`Organized`, ],
  },
  {
    id: 9,
    url: `ice-blocking`,
    name: `Ice Blocking`,
    spaces: [`Outdoors`, ],
    description: `Split group into two or more teams. Then within each team have players get into groups of three. This is a relay style race. Give each team an ice block and towel place on top of it. Place a cone a good distance in front of each team. Each team will have their first group get ready by having one player lie on their stomach on the block while the other two players hold their arms. When facilitator says go, the two standing players will run while pulling the player on the ice block, they must pull them to the cone, around the cone, and back. As soon as they get back to the team they switch out and the next group of three goes. The first team to get all of their groups around the cone and back wins. Game Twist: When players reach the cone, have the player on the block get off and switch with one of the pulling players for the return trip.`,
    events: [`Summer Camp`, `SGU`, ],
    settings: [`Organized`, ],
  },
  {
    id: 10,
    url: `fish-volleyball`,
    name: `Fish Volleyball`,
    spaces: [`Outdoors`, ],
    description: `A variation of volleyball played with dead fish. Split players into two teams, and have each player partner up with a teammate. Each pair is given a trash bag which they will hold stretched out between them. Then the teams use the bags to catch and throw a dead fish back and forth over a volleyball net. If the fish touches the ground, the scoring is like regular volleyball.`,
    events: [`Summer Camp`, `Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 11,
    url: `capture-the-cone`,
    name: `Capture the Cone`,
    spaces: [`Outdoors`, `Indoors` ],
    description: `Similar to capture the flag, players are split into two teams and each given half of the space. Instead of one flag, the team is given 5-8 cones which are placed in a line along the back of their team's territory. The goal is to get all of the cones onto your team's side. If a player is tagged on the opposing team's side, they sit down (instead of going to a jail), and can be rescued by one of their teammates tagging them, at which point both players get a free pass back to their own side. Defenders must remain 5-10 feet away from where the cones are (no puppy guarding). When an attacking player reaches an enemy cone, they may choose to stay there without fear of being tagged, so long as they are touching the cone, and the cone is touching the back line. As soon as they pick it up to run, they are again eligible to be tagged. If a player successfully returns a cone to their side, they must place it on their own back line. If a player with a cone is tagged, the cone remains there and is not returned to the back line. The safe zone rule only applies to cones on the back line, but the puppy guarding rule applies to all cones.`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 12,
    url: `trash-can-game`,
    name: `Trash Can Game`,
    spaces: [`Outdoors`, ],
    description: `Students and leaders stand in a circle holding hands. One or more empty garbage cans are placed in the middle of the group. Players must try to pull other players into the garbage can without touching it themselves or letting go of the players next to them. If a player touches the can, they are out. If the connection between to players is broken, both players are out. Last player standing wins. Consider separating groups by gender, depending on the group.`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 13,
    url: `dodgeball`,
    name: `Dodgeball`,
    spaces: [`Indoors`, ],
    description: `Split players into two teams and divide the playing space in half. Place dodgeballs along the dividing line and have each team wait at the back of their side. When the facilitator says go, the teams may run to get the balls and play begins. Optionally, the facilitator may give players a 5 second safety window to retrieve the balls without fear of getting hit. Players try to hit members of the opposing team with balls while staying on their own side. If a player gets hit with a ball they are out (unless they get hit in the head) and must form a line on the sideline with their other teammates who are out. Players may deflect balls with a ball they are holding. If a player catches a ball thrown at them the thrower is out and the first player in the catching team's "out line" may rejoin the game. If the ball bounces on the ground it is dead even if it hits a player after the bounce. The referee may choose to call jail break at anytime, in which case everyone who was out is back in the game. The team to eliminate all members of the opposing team wins. Game Twist: Mushroom style, no teams and no sides. If a player gets out they take note of who got them out and may return to the game when that player gets out. In this mode, players may only take 3 steps while carrying a ball.`,
    events: [`Youth Group`, `Fall/Winter Retreat`, `SGU`, ],
    settings: [`Organized`, ],
  },
  {
    id: 14,
    url: `cut-throat-mafia`,
    name: `Cut Throat Mafia`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Ideally, you need a somewhat dark space with obstacles or multiple rooms to impair sight lines. Before starting, 2-4 players are secretly selected to be the mafia. Play then begins and players move around the space casually interacting with one another. The mafia may "kill" a player by sliding a finger or hand across another player's throat. Generally speaking mafia should try to do this as inconspicuosly as possible. If a player is killed that person should continue to walk around for about 10 seconds (in order to avoid making it painfully obvious who killed them), and then fall to the floor. When a living player finds a player "dead" on floor, they call "dead body!" to the rest of the group. At this point all player convene a town hall around the dead player. The facilitator then asks for an accusation, and one player accuses another of being the killer. If another player seconds the accusation, the defendant is given a short amount of time to defend themselves. The group then votes on whether or not to kill the defendant, needing a majority to pronounce them guilty. If a majority is not achieved, one more accusation can be made, but no more than one conviction or two accusations should take place per town hall. Players do not reveal whether or not they are mafia when they die, but the facilitator knows who the mafia is. Play then resumes and the process repeats until either all the mafia are eliminated or are the only ones left. Mafia do not know who the other mafia are, and thus are also vulnerable to being killed by another mafia. If the space allows, a mafia may escort a dead body to a hiding place in order to keep them from being found. The dead body should play along and go with them, but the mafia does risk being seen "stashing" the body. At the end of a town hall, all dead players should return to a desingated space for them to watch. Dead players may not give any insight to the living. Game Twist: If in a smaller space, have mafia kill people by sticking a tongue out at them (àla killer frogs) rather than sliding a finger across their throat.`,
    events: [`SGU`, `Sunday School`, ],
    settings: [`Organized`, ],
  },
  {
    id: 15,
    url: `garbage`,
    name: `Garbage`,
    spaces: [`Indoors`, ],
    description: `Divide players into 3-4 teams. Use false walls or other tall barricades to seperate the teams from one another. Give each team a large number of balls and other soft items. When the facilitator says go, each team tries to get rid of all their "garbage" by throwing it over the barricades into the other team's zones. The first team to empty their zone of garbage wins. If no team achieves this, the team with the least amount of garbage at the end of the time wins.`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 16,
    url: `protect-the-president`,
    name: `Protect the President`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Have players stand in a wide circle with two people in the middle. One person in the middle is the President, the other is the Bodyguard. The players in the circle have a soft dodgeball, and try to hit the President with it. The bodyguard may jump, squat, dive, etc in order to deflect the ball before it hits the President. If the ball touches the President at any time, the person who threw the ball (or the last person to touch it) then becomes the bodyguard, the bodyguard becomes the President, and the President goes back into the circle. What makes this exciting is that from the moment the President is hit, the new President is vulnerable because the transition is instantaneous. The new bodyguard must be fast at getting into the circle to defend him or her. This sometimes makes presidential turnover pretty quick, but it's exciting. Game Twist: Add multiple balls and/or bodyguards.`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 17,
    url: `sharks-and-minnows`,
    name: `Sharks and Minnows`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `All players line up on the edge of the playing field/room (“ocean”). Select a few players to be the “sharks”. The sharks will yell go and the players ("minnows") must run across the ocean to the other side. Their goal is to make it safely to the other side without getting tagged by the sharks. The sharks goal is to tag as many minnows as possible. If a minnow gets tagged they must stop wherever they are at and they become “seaweed”. As seaweed they may not move their feet, but may move their arms and torso and try to tag minnows that run by them. If the playing space is crowded, have the minnows sit down. Play continues until there is a winning minnow!`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 18,
    url: `car-lot`,
    name: `Car Lot`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Very similar to sharks and minnows. Divide players into 4 groups and send each group to one corner of the space. Name each group a different type of car, then select 2-3 players from the entire group to be "car salesmen". The car salesmen stand in the center. The facilitator calls out 1 or 2 car types, and those groups must run to the corner opposite of the one they are currently in. The car salesmen try to tag the players as they run. If tagged, the player must sit down and can try to tag others but may not move to do so. If the facilitator calls "Car Lot!" all players run. The last player not to be tagged wins.`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 19,
    url: `steal-the-bacon`,
    name: `Steal the Bacon`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Players are split into 2-4 groups and then numbered off within each group. So if there are 40 players and two teams there would be 20 players per team numbered 1-20. Groups then are placed on different sides of playing area. In the middle an object (or objects) is placed. This is the “bacon”. A facilitator then calls out a number and the player with that number from each team races to get the object(s) and get it back to their teams side, earning a point for their team. As play continues, the facilitator may make play trickier by calling multiple numbers, a number range, or a type of number (prime, multiples of 5, etc) thus having more players race for the “bacon”. Game Twist: Players must avoid being tagged by the other team while returning the bacon to their own team.`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 20,
    url: `the-bacon-game`,
    name: `The Bacon Game`,
    spaces: [`Indoors`, ],
    description: `Have players spread out in a large space. The facilitator will yell out a number between 1 and 5. If he says #1, everyone has to lie down on their back as fast as they can and sizzle like bacon. #2 means that everyone needs to find a partner to do a piggy back with. #3 means that everyone needs to find 2 other people to do a pyramid with. #4 means that everyone needs to find 3 other people to line up, sit down with, and pretend to be rowing a canoe with. #5 means that everyone needs to find 4 other people to make a star with by raising up and putting their hands together. Everyone will try to fulfill these commands as fast as possible. If they take too long, can’t find the right amount of people (too many or too few),or if do the wrong command, then they will be out. There will be leaders watching to judge whether people are out or not. The game continues until you have a winner. The numbers can be repeated, said as many times as one desires, and can be out of order (all highly encouraged). When a person is out, they go to the outskirts of the room to watch.`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 21,
    url: `line-soccer`,
    name: `Line Soccer`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Players are divided into two teams, and each team lines up along one side of a playing area. The playing area has a goal at either end and soccer ball is placed in the middle. Players are numbered off within their team. A facilitator then calls out a number and the player with that number from each team run onto the field and attempt to score by kicking the ball into the other team's goal, earning a point for their team. As play continues, the facilitator may make play trickier by calling multiple numbers, a number range, or a type of number (prime, multiples of 5, etc) thus increasing the number of players on the field. Players on the sides may also kick the ball, but only if it comes to them, as they cannot cross the sideline. The team with the most points after the last round wins.`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 22,
    url: `mega-tic-tac-toe`,
    name: `Mega Tic Tac Toe`,
    spaces: [`Indoors`, ],
    description: `Divide players into two teams and have them stand in a line at one end of the playing area. Give each team 3 or 4 large markers. At the other end of the playing area, setup a large 9 square grid. When the facilitator says go, the first person on each team takes a marker, runs down and places into a square on the grid. They run back and the next person on their team repeats the process. The first team to get three markers in a row wins the round. Once all markers are on the grid, players must move one their team's markers each trip down.`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 23,
    url: `fruit-basket-upset`,
    name: `Fruit Basket Upset`,
    spaces: [`Indoors`, ],
    description: `Everyone forms a circle with their chairs, making sure that there is one less chair than the number of people playing. Whichever player does not have a chair starts in the middle. Everyone sitting down will pick a fruit (you can either leave it open for everyone to decide or make them pick from three of four options). The person in the middle will call out a fruit and everyone who chose that fruit will get up and run to a new seat at least three chairs away. The person in the middle will also run to a seat. Whoever is left without a seat is the new caller. The caller can at any point call “fruit basket upset”. When this is called everyone must get up and find a new seat.`,
    events: [`Sunday School`, `Fall/Winter Retreat`, ],
    settings: [`Organized`, ],
  },
  {
    id: 24,
    url: `rock-paper-scissors-train`,
    name: `Rock Paper Scissors Train`,
    spaces: [`Indoors`, ],
    description: `Each person finds a partner and plays rock, paper, scissors with them. The loser must stand behind the winner with his hands on the winners shoulders and chant the winners name. The winner will then find another winner (with the loser still attached to them). The loser of that match will link on the back of the winners train and anyone who was on their back will follow and they will all chant the new winners name. This continues until there is one winner and a long train.`,
    events: [`Sunday School`, `Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 25,
    url: `the-king-desires`,
    name: `The King Desires`,
    spaces: [`Indoors`, ],
    description: `One person is “the king” and the rest of the players split into teams of about 5 people. The king will then ask for specific items from the group (i.e. a nail file, a key to a Toyota, an iPod playing a popular song, a shoe from every member in the group, etc…). The groups will then send one member as a representative of their group with the requested item. Whichever team reaches the king with the correct item first wins. This game can be played with points, or just for fun.`,
    events: [`Sunday School`, ],
    settings: [`Organized`, ],
  },
  {
    id: 26,
    url: `i-love-my-neighbor-who`,
    name: `I Love My Neighbor Who...`,
    spaces: [`Indoors`, ],
    description: `Everybody grabs a chair and makes a giant circle. One person is chosen to start out in the middle, their chair is removed, and they say something like “I love my neighbor who... is wearing red”. Anyone who is wearing red has to get up and switch to a different seat (but not one of the seats right next to them). The person who does not get a seat now stands in the middle and says “I love my neighbor who... _____” and fills in the blank.`,
    events: [`Sunday School`, ],
    settings: [`Organized`, ],
  },
  {
    id: 27,
    url: `shuffle-your-buns`,
    name: `Shuffle Your Buns`,
    spaces: [`Indoors`, ],
    description: `Players start sitting in a circle all facing inward. One person is selected and stands up in the middle of the circle, leaving one empty chair in the circle. The person in the middle tries to sit in the empty seat. The people sitting down have to slide to the empty chair to their side. If the person gets in the seat then whoever was suppose to move now is in the middle. While playing, leader yells switch and the group changes the direction they were moving. Game Twist: Have multiple people in the middle and/or multiple openings in the circle.`,
    events: [`Sunday School`, ],
    settings: [`Organized`, ],
  },
  {
    id: 28,
    url: `the-name-whapper-game`,
    name: `The Name Whapper Game`,
    spaces: [`Indoors`, ],
    description: `Players sit in a circle. One player is standing in the middle holding a pool noodle. A player sitting in the circle stands up and calls out their own name, then someone else’s name and then sits down. The player with the pool noodle tries to hit the player whose name has been called. The player who has their name called must stand and call out their name and someone else's name before they are hit with the pool noodle. If a player whose name is called gets hit before they can call out both names, the hit player then goes in the middle and has the pool noodle and the prior middle person takes their spot in the circle. The former middle person must call a new person’s name before sitting down or they may be hit and placed in the middle again.`,
    events: [`Sunday School`, ],
    settings: [`Organized`, ],
  },
  {
    id: 29,
    url: `four-corners`,
    name: `Four Corners`,
    spaces: [`Indoors`, ],
    description: `Before the game, designate each corner of the room a number 1-4. One person is selected to be the "picker" and they are placed in the middle of the room with their eyes covered. At the beginning of each round, players have 10-30 seconds to go to one of the corners of the room, depending on the size. After the time seconds is up, the picker says one of the numbers. Whoever is in the corresponding corner is eliminated from the game. Players then have the same amount of time to select a new corner. The picker then again says one of the four numbers. This process continues until there is only one player left. Game Twist: For large groups, have only the players in the selected corner remain, and eliminate the players in the other three corners.`,
    events: [`Youth Group`, `Sunday School`, ],
    settings: [`Organized`, ],
  },
  {
    id: 30,
    url: `my-grandmothers-big-fat-toe`,
    name: `My Grandmother's Big Fat Toe`,
    spaces: [`Indoors`, ],
    description: `Groups of 10-20 players form circles and choose one start person. That person will turn to the person on their right and ask a question. The person who they asked must respond with “My grandmother’s big fat toe”. The person who answered will then turn to the person on their right and ask a new question, to which the person asked must respond “My grandmother’s big fat toe” and so on. The trick is that you cannot smile or laugh while asking, answering, or being asked a question. If someone does so they are out. If someone repeats a question that has already been asked they are out. Players must make eye contact when asking or answering a question. If someone hesitates before answering they are out, though giving a more elaborate answer that includes the phrase is acceptable. Last player standing wins.`,
    events: [`Sunday School`, ],
    settings: [`Organized`, ],
  },
  {
    id: 31,
    url: `museum`,
    name: `Museum`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Select one player or leader to be the night watchman. All other players are statues and choose a spot to start in the playing space. Once they pick a spot, the watchman places a few items around the space. The round begins and the players must complete some task with one of the objects. For example, if playing in a room with a whiteboard, the watchman could place markers which the players would have to retrieve and then use to write their name on the board. Or if in a park, balls could be spread out and the players would have to retrieve one and take it to a certain spot. The first player to complete the task wins the round and becomes (or gets to pick) the next night watchman. The catch is that if the night watchman sees any of the "statues" moving, they eliminate that player, so players must be careful to only move when the night watchman can't see them. If a player has an item when they are caught, the item is dropped where that player was.`,
    events: [`Sunday School`, `MS Summer Hangout`, ],
    settings: [`Organized`, ],
  },
  {
    id: 32,
    url: `killer-frogs`,
    name: `Killer Frogs`,
    spaces: [`Indoors`, ],
    description: `Have all players sit in a circle. The facilitator secretly chooses a few players to be killer frogs. Play begins and players look around the circle and make small talk with one another. The killer frogs try to inconspicuosly kill players by sticking their tongue out at another player while making eye contact. If a player is killed he/she falls to their death in the middle of the circle. Players try to guess who the frogs are during the course of the game. If a player guesses correctly, the frog dies, but if they guess wrong the guessing player dies. The round ends once all the frogs are dead or are the only ones remaining. Game Twist: Frogs kill by winking at a player while making eye contact rather than sticking out there tongue.`,
    events: [`Sunday School`, ],
    settings: [`Organized`, ],
  },
  {
    id: 33,
    url: `lava-monster`,
    name: `Lava Monster`,
    spaces: [`Outdoors`, ],
    description: `Meant to be played on a jungle gym. One player is selected to be the lava monster. They must remain on the ground. To all other players, the ground is lava and cannot be touched. The lava monster tries to tag one of the players on the jungle gym. If they do, that player becomes the new lava monster.`,
    events: [`MS Summer Hangout`, ],
    settings: [`Freetime`, ],
  },
  {
    id: 34,
    url: `psychologist`,
    name: `Psychologist`,
    spaces: [`Indoors`, ],
    description: `Pick one or two members of the group to be "psychologists". Have them step outside the room and have the rest of the group decide on one "condition" that all players will have. The condition can be anything: medical, social, or totally crazy. Some example conditions include: all players are pregnant, all players are shy, all players are on a pirate ship, all players are a different member of the group, etc. Creativity when choosing a condition is highly encouraged. Once the group has decided, have the psychologist(s) return. The psychologist(s) must ask questions of the group and try to guess what their "condition" is. Players should answer in chararter, but not so obvious as to make it too easy for the psychologist(s). Here is an example with the illness being that each answer begins with the next letter of the alphabet Question: Amber, what is your favorite color? Amber: Any color really Question: Mike, what did you do yesterday? Mike: Booked a vacation Question: Tanya, what did you have for lunch? Tanya: Cauliflower and Carrots Once the person thinks they have the illness figured out they can diagnose it – and once it is diagnosed correctly then they choose a new psychiatrist who leaves the room and a new illness is decided upon. They may guess as much as they like and continue asking questions until they have it.`,
    events: [`Sunday School`, `Ignite Project`, ],
    settings: [`Organized`, ],
  },
  {
    id: 35,
    url: `streets-and-alleys`,
    name: `Streets and Alleys`,
    spaces: [`Indoors`, ],
    description: `Players are divided into lines of 8-10, and line up arms length apart with their arms outstretched, forming rows (or streets). Two players are selected to run, one designated the chaser. The chaser chases the other player up and down the "streets" formed by all the other players. When the facilitator calls "alleys!" all the players rotate 90 degrees to form new rows (alleys) with the people who were behind and in front of them. This completely changes the playing field, potentially putting the chaser very close or very far away from the runner. The facilitator may yell "streets" or "alleys" as often as they like, changing the playing field each time. If the chaser tags the runner, the runner becomes the chaser and the former chaser chooses a nearby player to become the new runner. As play goes on the facilitator can add a second or third pair of runners/chasers to give more players the opportunity to run.`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 36,
    url: `pictionary-relay`,
    name: `Pictionary Relay`,
    spaces: [`Indoors`, ],
    description: `Ask everyone to sit in groups. Once each group has been given paper and a pen/pencil, the game leader tells each team to get a player ready who is going to start. The game leader leaves the room and wanders the building (or a portion of it). When the game starts the first player runs to find the game leader to get the first word. The player then runs back to his/her team and tries to draw that word out. When any of his/her teammates guess the word, a different player can run to the game leader to get the second word and repeat the process. The team that draws and guesses all of the game leader's words first is the winner.`,
    events: [`Youth Group`, `Christmas Party`, ],
    settings: [`Organized`, ],
  },
  {
    id: 37,
    url: `two-truths-and-a-lie`,
    name: `Two Truths and a Lie`,
    spaces: [`Indoors`, ],
    description: `Break off into small groups (4-6) and all players think up 2 facts about themselves and create one lie. Players take turns off listing off their facts/lie and the rest of the group tries to guess which one is the lie. Game Twist: Have players do two lies and one truth.`,
    events: [`Youth Group`, `Sunday School`, ],
    settings: [`Organized`, `Freetime`, ],
  },
  {
    id: 38,
    url: `a-walk-in-the-park`,
    name: `A Walk in the Park`,
    spaces: [`Indoors`, ],
    description: `Everyone will get into groups of 3-5 people. Groups form a large circle in the room, with the game leader on the outside. The game leader will then specify a location (i.e. the park, school, mars, a farm, etc…). The first group will run onto the “stage” (the area directly in front if the game leader) and have five seconds to silently perform an action that goes with the specified location. The leader will try to guess what they are doing in the five seconds. If the leader guesses in the time limit the group is still in. If the leader does not guess in the time limit or if the group repeats an action that has already been performed they are out and must sit down. The teams that are in continue to move around the circle, as each team runs on stage for their five seconds. The winner is the team last standing.`,
    events: [`Youth Group`, `Christmas Party`, ],
    settings: [`Organized`, ],
  },
  {
    id: 39,
    url: `blob-tag`,
    name: `Blob Tag`,
    spaces: [`Indoors`, ],
    description: `Also known as 'Amoeba Tag'.In this variation of tag, you start with one player it. When they tag another player, they link together either by elbows or holding hands and are now both it. Anytime a player is tagged they join the chain until everyone is a part of the "blob".`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 40,
    url: `link-tag`,
    name: `Link Tag`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Players choose a partner and link arms. The pairs then space out and stand in a large circle. One set of players is chosen to start. One is “it” and chases the other player in a tag-like fashion. The player being chased may choose to link up with any pair standing around the circle. When they link up with someone, the player who is already linked to that player must break off and the player who is “it” must now chase them. If the tagger tags the player they are pursuing, play reverses and the tagged player is now “it” and the other is now running away. Once the group has the basics down, more pairs can be released to chase. Game Twist: Have players get into groups of three and have pairs stay linked while chasing/running. When pair links up with a group of three, the end two break off and remain linked to each other while running.`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 41,
    url: `human-foosball`,
    name: `Human Foosball`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Play just like the table game only with real people linked in rows. Split players into two teams, have a captain decide who goes in which rows and how many in each row. Each entire team faces one direction and has to stay that way. They link arms by holding the person's elbows next to them. The whole row has to stay within their boundaries like in the game, but they can slide back and forth, left and right. When you play inside you can mark the boundaries with masking tape, or if you play outside you can use paint (if acceptable) or tape or flour. If you play in a building, you need to remove pretty much everything from the room. If you play outside, it is best if you play between two buildings so that the ball stays in the game. If you play in a field, have lots of folks around to toss the ball back into play. Make sure everyone is wearing shoes, it can get a little fierce with the kicking. Stress safety and not getting out of control. Also, use a ball that is soft. Game Twist: Add multiple balls.`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 42,
    url: `heads-up-7-up`,
    name: `Heads Up 7 Up`,
    spaces: [`Indoors`, ],
    description: `Seven students are chosen as it. The rest of the room closes their eyes and lowers their heads. The seven go out and each tap one person on the head. Then the seven return to the front of the room and say "heads up seven up" and everyone looks up. Each student who got tapped on the head gets one chance to guess which of the seven touched him/her. If they guessed right than they changed places and become one of the seven. If they do not the same person gets to stay up.`,
    events: [`Sunday School`, ],
    settings: [`Organized`, ],
  },
  {
    id: 43,
    url: `group-juggling`,
    name: `Group Juggling`,
    spaces: [`Indoors`, ],
    description: `Form circles of 6-8 people. The starting person will toss a ball to anyone in the group who will then toss it to someone new, other than those standing right next to them. This will continue until everyone has been tossed the ball once. The last person will toss the ball back to the starting person. If you drop the ball you must start over. After going around once or twice in the same order, introduce multiple balls, keeping the order of who gets thrown to and if at any point a ball drops you must start over with all the balls.`,
    events: [`Youth Group`, `Fall/Winter Retreat`, ],
    settings: [`Organized`, ],
  },
  {
    id: 44,
    url: `gorilla-man-gun`,
    name: `Gorilla Man Gun`,
    spaces: [`Indoors`, ],
    description: `A variation of Rock, Paper, Scissors, may be played with any group size. Players pair up and stand back to back. Facilitator starts the rhyme of “Gorilla beats the man, man beats the gun, gun beats gorilla, if you tie you die. One two three.” After three plays turn around and act in one of three ways. 1. Man = scratching chin. 2. Gun = either hand pistol or acting like holding a rifle. 3. Gorilla = Hands over head in a gorilla like fashion. Following the rules of the rhyme, losing players sits down, if a tie both players are out. Winners find a new partner and play continues until there is one person left.`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 45,
    url: `ninja`,
    name: `Ninja`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `All players stand in a circle and on the count of three, step back and strike a ninja pose. Players MAY NOT MOVE unless it is their turn or they are dodging. Choose a player to start. This player may either change position or attack another player by attempting to hit one of their hands. Either type of move must be done in one fluid motion. If a players hand gets hit, their hand is out and they must keep it behind there back and may no longer use it in game play. If both of a players hands get hit, they are out of the game. Play continues one by one, going clockwise based on where the players orinally started the game. If a player is attacked, even if it is not their turn, they may dodge the attack by moving in one fluid motion. Play continues until one player is left standing.`,
    events: [`Youth Group`, `Summer Camp`, `Fall/Winter Retreat`, `Ignite Project`, ],
    settings: [`Freetime`, ],
  },
  {
    id: 46,
    url: `signs`,
    name: `Signs`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Players sit in a circle and everyone comes up with a sign for themselves. Scratch your cheek, flip your hair, etc. Go around and demonstrate your sign for the group. One person will start and silently pass their sign along without the designated person in the middle catching you doing the sign. Players recieve the sign by first doing their own sign, then pass it by doing another person's. Once that person does their own sign, they now have the sign and must pass it. Players may continue to do the other person's sign if the recipient didn't see it. Players have to watch carefully as the sign can move quickly. If the person in the middle finds out who has the sign, that person is now in the middle.`,
    events: [`Sunday School`, `Fall/Winter Retreat`, ],
    settings: [`Organized`, `Freetime`, ],
  },
  {
    id: 47,
    url: `smash-face`,
    name: `Smash Face`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Players stand in a circle, with one player selected to start sitting in the middle. The players on the outside bump a volleyball or other softball amongst themselves. After three or more bumps or sets have been made, someone on the outside may try to hit the person(s) in the middle with the ball. If they succeed and then the ball hits the ground or an outside player, the round is over and a new one begins. If at any point during a round, the player(s) in the middle catch the ball, they are out of the middle and the last outside person to touch the ball is now in the middle. If the ball hits the ground without hitting the player in the middle (whether in passing or in an attempt to hit the player(s) in the middle), the last outside player to touch the ball joins the group in the middle. A player may avoid this if it was clearly another outside player's fault that the ball hit the ground,in which case that player would go into the middle instead. This desicion is highly subjective and usually left up to the group or involved parties to work out.`,
    events: [`Summer Camp`, `Youth Group`, `Ignite Project`, `Fall/Winter Retreat`, ],
    settings: [`Freetime`, ],
  },
  {
    id: 48,
    url: `gaga-ball`,
    name: `Gaga Ball`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `All players stand in an octagonal arena with 2-3 foot walls. Laying 8 folding tables on end is an easy way to make an arena. All players start touching a wall, and a ball is tossed in to the middle. Once the ball bounces twice, play begins. Players try to eliminate other players by hitting the ball at them below the waste. If the ball touches any part of a player below the waist, they are out and must stand on the outside of the octogon. Players may not sit/kneel/lay on the ground as a form of defense, though squatting is fine. If the ball goes outside of the octogon and hits the ground, the last person who touched is out. If a player on the outside catches it before it hits the ground, they take the spot of the last inside player the ball touched. Players on the outside may not reach over the wall to catch a ball. If the ball hits a player on the outside and bounces back into the octogon, no one is out. The last player standing in the octogon wins.`,
    events: [`Fall/Winter Retreat`, `Youth Group`, ],
    settings: [`Freetime`, ],
  },
  {
    id: 49,
    url: `nine-square`,
    name: `Nine Square`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Pretty much the same as traditional 4 square, but with a grid of 9 squares instead. The player in the middle square is King or Queen and starts the round by tossing the ball to one of the players in the other squares. This initial toss must be easily playable. Players continue hitting the ball into other player's squares until one player is out. A player can get out by: 1) hitting the ball outside of all 9 squares 2) hitting the ball multiple times before the ball hits anything else 3) hitting the ball into his/her own square 4) having the ball bounce once in his/her own square and then bounce outside of all 9 squares 5) having the ball bounce twice in a row in his/her square, with no other player touching it in between bounces. The player whose it out goes to the back of the line, and everyone who was behind that player moves up one square, with the center square being the "highest" square, and a new round begins. Players must hit the ball rather than grab or throw it (the ball cannot rest on/in a player's hand(s) while in motion). If the ball hits any part of the body it counts as a hit. If there is a dispute as to which player is out, various methods may be used to resolve it including a redo of the round, though generally if someone leaves there square other than to get the ball, it is considered an acceptance of being out.`,
    events: [`Youth Group`, `Hello Goodbye Party`],
    settings: [`Freetime`, ],
  },
  {
    id: 50,
    url: `wax-paper-relay`,
    name: `Wax Paper Relay`,
    spaces: [`Indoors`, ],
    description: `Divide players into teams. Each team then divides into sub-teams of 3. The sub-team gets two pieces of wax paper. Place a cone a distance away in front of each team. This is a relay game. One member of each sub-team stands on the wax paper and the other two drag him/her around the cone and back to their waiting team and sits down. As soon as the first sub-team gets back the next sub-team goes. The first team to have the last sub-team make it around and back wins.`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 51,
    url: `red-light-green-light`,
    name: `Red Light Green Light`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Players line up at one end of playing area. One player (the traffic light) stands at the opposite end and calls out either “green light” (faces away from the crowd) or (faces towards the crowd) “red light”. When Green light is called players run towards the traffic. When red light is called all players must freeze. If a player continues moving/running when red light is called they must return to the starting line. The first player to touch the traffic light wins and becomes the next traffic light. Game Twist: The traffic light can call out other things beside "red light"/"green light" to try and get players to jump.`,
    events: [`Youth Group`, `MS Summer Hangout`, ],
    settings: [`Organized`, `Freetime`, ],
  },
  {
    id: 52,
    url: `saltine-cracker-relay`,
    name: `Saltine Cracker Relay`,
    spaces: [`Outdoors`, ],
    description: `Players are divided into teams of equal size, and stand in a line with their team. Each team member is given one or two saltine crackers (the dryer the better). When the game leader says go, the first player on each team must eat their crackers and then try to whistle as quickly as possible. Once they whistle (loud enough to be heard by someone else), the next person in line begins the same task. The team whose last player whistles first wins.`,
    events: [`Summer Camp`, ],
    settings: [`Organized`, ],
  },
  {
    id: 53,
    url: `cheetoh-toss`,
    name: `Cheetoh Toss`,
    spaces: [`Outdoors`, ],
    description: `Split group into two teams and have them line up in single file lines. Have a volunteer from each team stand a little in front of the line and cover their face with whip cream. The teams then work through the line, each player throwing a cheeto and trying to make it stick to their teammate's face. The winning team is the one that gets the most to stick.`,
    events: [`Summer Camp`, ],
    settings: [`Organized`, ],
  },
  {
    id: 54,
    url: `red-rover`,
    name: `Red Rover`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Players are split into two teams. Each team holds hands in a long line, with one team on each end of playing space. The first team then chooses a player from the other team and yells “Red Rover, Red Rover, send __insert name of chosen player___ on over.” The player whose name is called must run and go between two players on the other team, trying to break their hands apart. The players who he/she runs between must try to remain connected. If the player is successful in breaking through the other players, they may choose a player to bring back to their team with them. However, if they are unsuccessful, they join the team that called them. Teams alternate turns until all players are on one team. `,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 55,
    url: `screaming-sprint`,
    name: `Screaming Sprint`,
    spaces: [`Outdoors`, ],
    description: `Have everyone line up along a field or large room. When the facilitator says go, all players will run as far as they can. The catch is they may only take one breath and must scream at the top of their lungs while running. When they stop screaming or run out of breath they must stop. Eliminate all players who do not reach a predetermined distance. Have remaining players line up and play again, continuing to eliminate about half each round until you have a winner or a handful of winners.
    Game Twist: Split players into teams. Have a lengthy predetermined distance (impossible for only one person to do) and have one player at a time go as far as they can, the next teammate must start where the first one stopped and run from there. They must reach the distance within a certain number of people or start over. The first team to reach the end wins.`,
    events: [`Hello Goodbye Party`, `Youth Group`],
    settings: [`Organized`, ],
  },
  {
    id: 56,
    url: `go-event`,
    name: `Go! Event`,
    spaces: [`Indoors`, ],
    description: `Massive themed event. Students will be divided into three teams and start in the fellowship hall. Each team will have an empty garbage bin at the west end of the sanctuary. The sanctuary, foyer, and all three levels of the CM wing will have small squares of cardstock paper spread all over the floor (with exceptions for rooms we don’t want students in). Each team will attempt to find and return as many pieces of paper as possible to their bins during the round. Each student may carry up to five pieces at a time. At the end of each round, leaders will count the number of papers in each teams bin which will eventually be totaled to determine which team is the winner. During the round, leaders will wander the halls attempting to capture students by shooting finger rockets at them. If a student is hit with a rocket they must drop their papers and go to the jail, marked off in the sanctuary. Students may not pick up or use finger rockets. One leader will be a "boss". The boss will roam the facility with some extra power or weapon that will be much harder for the students to escape. A student may rescue another member of his/her team from jail by going to the jail and paying three pieces of the plans to the jail minder. Students will be released in the order they arrived, per team, àla dodgeball rules. Usually a few members of each team will be given something to help protect their teammates. There is also usually a bonus that students can earn for their team during the round. Many of the specific rules and gameplay features are built around the theme. Past events include: "Go Bananas", "Go Hobbits", Go Star Wars", "Go Mario", and "Go CIA".`,
    events: [`Go! Event`, ],
    settings: [`Organized`, ],
  },
  {
    id: 57,
    url: `blurt-or-squirt`,
    name: `Blurt or Squirt`,
    spaces: [`Outdoors`, ],
    description: `A student "who is good at talking" is selected to come up in front of the group. The entire group is asked to come up with a topic for the student to talk about. The student will have to talk about that topic non stop for 30 seconds. Any time he or she stops talking or says "um, er, uh, etc." then he or she will by squirted by a squirt gun held by the game leader. Multiple students can be chosen to take turns coming up on stage and to raise the stakes, the game leader can take out a bigger squirt gun each time!`,
    events: [`Hello Goodbye Party`, ],
    settings: [`Organized`, ],
  },
  {
    id: 58,
    url: `train-wreck`,
    name: `Train Wreck`,
    spaces: [`Indoors`, ],
    description: `Each player is given a chair and forms columns facing the front of the room. The facilitator is at the front and assigns each column a number or letter. The facilitator calls a column and everyone in that column must get up and run to the front, around the side of all the columns and back into a seat in their column. The facilitator also runs, thus leaving one player without a seat. They then go up to the front and call a different column and the process repeats. The caller can call one or multiple columns. If the caller yells "train wreck!" then every column gets up and runs, and players may take a seat in any column.`,
    events: [`Youth Group`, `Christmas Party`, ],
    settings: [`Organized`, ],
  },
  {
    id: 59,
    url: `dragon-tail`,
    name: `Dragon Tail`,
    spaces: [`Indoors`, ],
    description: `Students form "dragons" by grouping up into groups of three or four. Students must stay attached to their "dragon" group by putting their hands on the shoulders of the person in front of them. Each group is given a bandana that the student in the back must put the in their back pocket with it half-way out. The student in the front leads the "dragon" group and tries to pull the "tails" off of the other "dragons." Only the front student may pull on tails. If a groups tail is pulled off they are out. The last group standing wins. Have the order of the players in each "dragon" rotate in subsequent rounds`,
    events: [`Youth Group`, ],
    settings: [`Organized`, ],
  },
  {
    id: 60,
    url: `sit-down-mafia`,
    name: `Sit Down Mafia`,
    spaces: [`Indoors`, ],
    description: `Before play, designate a narrator. Hand every other player a playing card representing their role. Depending on group size, have 1-2 doctors, 1-3 mafia, and 1-2 policemen, everyone else will be townspeople. Shuffle and pass out the cards and make sure that no one shows anyone else their card. The narrator then asks everyone to go to sleep. At this point everyone closes their eyes and puts their heads down. The narrator then asks for the mafia to wake up. All the mafia silently look up and open their eyes. The narrator asks who they want to kill, and they silently all point and decide on one person to kill. The narrator then asks the doctor(s) to wake up, they all silently “wake up”. The narrator asks them who they want to save. They must silently decide to save one person from the mafia. The narrator then tells them to go back to sleep and has the policemen wake up. The narrator asks them who they think the mafia is, they all silently agree on one person and the narrator nods yes or no to indicate if they are correct. The narrator then has them go back to sleep and asks everyone to wake up. Everyone wakes up and the narrator tells a funny/dramatic tale of how whoever the mafia chose to kill dies. However, if the doctors chose to save the right person their tale will not end in death. Then the narrator facilitates a mock trial as the players try to guess who is the mafia, once a “suspect” is chosen, the group votes and if the majority is a yes, that player is dead whether they are mafia or not. At that point they may tell the group what their role was. If the majority is no, they choose another suspect. Once the trial is done, the narrator tells everyone to go to sleep and the next round begins. If all the mafia are caught, the townspeople win, if the mafia are the last one alive, they win. "Dead" people may watch but not give away any information.`,
    events: [`Summer Camp`, `Fall/Winter Retreat`, `SGU`, ],
    settings: [`Freetime`, ],
  },
  {
    id: 61,
    url: `look-up-look-down`,
    name: `Look Up, Look Down`,
    spaces: [`Indoors`, ],
    description: `Arrange participants into groups of 12-20 members. Have participants stand in a tight circle, shoulder to shoulder. When you say "look down" everyone must look at the ground, and when you say "look up" everyone must look up and stare directly at the face of another person. If two people look up and stare at each other, they each "lose" (have to cover) one eye. The rest of the participants who didn't make eye contact with another person will continue staring until the facilitator says, "look down" again. If a player loses both eyes they are eliminated and must step out of the circle. Play continues until there are only 1 or 2 people left in the circle.`,
    events: [`Summer Camp`, `Fall/Winter Retreat`, `Sunday School`, ],
    settings: [`Freetime`, `Organized`],
  },
  {
    id: 62,
    url: `fun-on-a-table`,
    name: `Fun on a Table`,
    spaces: [`Indoors`, `Outdoors`],
    description: `Have two "spotters" stand at the ends of a folding table. They do not touch the table, they merely are there to catch it if it starts falling. Then an individual tries to climb completely around the table without touching the ground. If they touch the ground they are done and must start over. `,
    events: [`Summer Camp`, `Fall/Winter Retreat`, `Ignite Project`, ],
    settings: [`Freetime`, ],
  },
  {
    id: 63,
    url: `human-knot`,
    name: `Human Knot`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Form groups of about 10 people each. Have each group stand facing each other shoulder to shoulder in a circle. First, instruct everyone to lift their left hand and reach across to take the hand of someone standing across the circle. Next, have everyone lift their right and reach across to take the hand of another person standing across the circle. Make sure that no one is holding hands with someone standing directly beside the person. To play, the groups must communicate and figure out how to untangle the knot (forming a circle of people) without ever letting go of any hands. `,
    events: [`Youth Group`, `Sunday School`, `Summer Camp`, `Fall/Winter Retreat`, `Ignite Project`, `MS Summer Hangout`, ],
    settings: [`Organized`, `Freetime`, ],
  },
  {
    id: 64,
    url: `king-of-the-raft`,
    name: `King of the Raft`,
    spaces: [`Outdoors`, ],
    description: `Your basic king of the hill game. Put an inflated paddle raft a short distance from shore (ideally in water 2-3 feet deep), upside down. Players all start on the raft and when the facilitator calls game start, all players attempt to push or throw other players off of the raft. If a player falls into the water they may get back on the raft and continue playing or they may attempt to pull players off the raft. When a player is the only one on the raft, they get points for how long they are standing without anyone else on the raft. At the end, whichever player stood alone the longest wins! Stress safety as a priority when explaining.`,
    events: [`Summer Camp`, ],
    settings: [`Organized`, ],
  },
  {
    id: 65,
    url: `extreme-rock-paper-scissors`,
    name: `Extreme Rock, Paper, Scissors`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `For any size group. Split into two teams. Each team huddles as a group and determines a play (rock, paper, or scissors). Both teams then line up in the center of the playing field facing each other. A facilitator counts to three and then both teams act out their play. (Scissors = Cutting motion with arms. Rock = growl and put arms in front in a roundish shape as if flexing. Paper = Arms straight above head.) Rules follow similar rock, paper, scissors. Rock beats scissors, scissors beats paper, paper beats rock. The winning team must then try to tag players from the other team while the losing teams tries to make it safely back to their line without getting tagged. If a player is tagged they join the other team and teams re-gather for next round. Game Twist: Tagged players are out rather than join the other team. Play continues until one team is eliminated.`,
    events: [`Youth Group`, `Hello Goodbye Party`, ],
    settings: [`Organized`, ],
  },
  {
    id: 66,
    url: `birdie-on-a-perch`,
    name: `Birdie on a Perch`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `All players are asked to find a partner. Upon finding a partner, the facilitator should find some way of distinguishing who is the "birdie" and who is the "perch". The "perches" then form a circle and the "birdies" form a larger circle around them. When the music starts, the circles walk opposite of one another so that partners are no longer together the whole time. The facilitator then stops the music and the "birdies" and "perches" need to find their corresponding partner as fast as possible. The "perch" should get down on one knee and the "birdie" should sit on the "perch's" raised knee. The last few pairs to find one another and assume the "birdie on a perch" position are eliminated from the game. Rounds are repeated until one pair wins. Game Twist: Can also play by calling out body parts to touch such as “elbow to nose!”`,
    events: [`Youth Group`, `Fall/Winter Retreat`, ],
    settings: [`Organized`, ],
  },
  {
    id: 67,
    url: `bump`,
    name: `Bump`,
    spaces: [`Indoors`, `Outdoors`, ],
    description: `Players line up in a single file line from the free throw or three point line in front of a basketball hoop. The first two players are given basketballs. The first player shoots and continues shooting (from anywhere after the first shot) to try and make a basket. The second player then does the same. If the second player makes a basket before the first player, the first player is “bumped” and is out of the game. The balls are then passed to the next two players. However, if the first player makes a basket before the second player, they pass their ball to the next player in line and that player then tries to make a basket before the player still shooting. Play continues until there is a winner. Players are allowed and encouraged to bump the other shooter's ball away from or out of the hoop with their ball in order to increase their own odds.`,
    events: [`Youth Group`, `Fall/Winter Retreat`, ],
    settings: [`Freetime`, ],
  },
  {
    id: 68,
    url: `balloon-tag`,
    name: `Balloon Tag`,
    spaces: [`Indoors`, ],
    description: `Tie a balloon to the ankle of each player, with enough slack on the string so that it moves around on the ground. Once all players have balloons, play starts. Players get other players out by stepping on their balloons and popping them. If a players balloon pops they are out. The last player standing wins.`,
    events: [`Sunday School`, ],
    settings: [`Organized`, ],
  },
];

export const GAMES = JSON.stringify(games);
